"""test2

Revision ID: 5e40d9d00190
Revises: c5a3b3efa0be
Create Date: 2023-04-13 14:56:27.540114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e40d9d00190'
down_revision = 'c5a3b3efa0be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_new', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='products'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products', schema='products')
    op.drop_table('customer', schema='customer')
    # ### end Alembic commands ###
