"""test8

Revision ID: 8b0ea93e7a10
Revises: bd5426ab4794
Create Date: 2023-04-13 15:26:27.021493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0ea93e7a10'
down_revision = 'bd5426ab4794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
